### Context

The number of restaurants in New York is increasing day by day. Lots of students and busy professionals rely on those restaurants due to their hectic lifestyles. Online food delivery service is a great option for them. It provides them with good food from their favorite restaurants. A food aggregator company FoodHub offers access to multiple restaurants through a single smartphone app.

The app allows the restaurants to receive a direct online order from a customer. The app assigns a delivery person from the company to pick up the order after it is confirmed by the restaurant. The delivery person then uses the map to reach the restaurant and waits for the food package. Once the food package is handed over to the delivery person, he/she confirms the pick-up in the app and travels to the customer's location to deliver the food. The delivery person confirms the drop-off in the app after delivering the food package to the customer. The customer can rate the order in the app. The food aggregator earns money by collecting a fixed margin of the delivery order from the restaurants.

### Objective

The food aggregator company has stored the data of the different orders made by the registered customers in their online portal. They want to analyze the data to get a fair idea about the demand of different restaurants which will help them in enhancing their customer experience. Suppose you are hired as a Data Scientist in this company and the Data Science team has shared some of the key questions that need to be answered. Perform the data analysis to find answers to these questions that will help the company to improve the business.

1. How many orders are not rated?
2. Which are the top 5 restaurant in terms of the number of orders received?
3. The company has decided to give 20% discount vouchers to the top 5 most frrequent customers. Find the IDs of these customers and the number of orders they placed.
4. Which is the most popular cuisine on weekends?

In [1]:
import pandas as pd
import numpy as np

print("Successfully Installed")

Successfully Installed

In [68]:
Food_hub_Order = pd.read_csv("foodhub_order.csv")
Food_hub_Order.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24

In [75]:
order_not_rated = Food_hub_Order[Food_hub_Order["rating"] == "Not given"]
print(order_not_rated.value_counts().sum())
print(order_not_rated.shape)

736
(736, 9)

In [27]:
top_5_restaurants = Food_hub_Order["restaurant_name"].value_counts().head(5)

print("top 5 restaurants:\n", top_5_restaurants)

top 5 restaurants:
 restaurant_name
Shake Shack                  219
The Meatball Shop            132
Blue Ribbon Sushi            119
Blue Ribbon Fried Chicken     96
Parm                          68
Name: count, dtype: int64

In [30]:
least_3_restaurants = Food_hub_Order["restaurant_name"].value_counts().tail(4)

print("least 3 restaurants:n", least_3_restaurants)

least 3 restaurants:n restaurant_name
Hiroko's Place      1
Frank Restaurant    1
Sarabeth's West     1
'wichcraft          1
Name: count, dtype: int64

In [26]:
top_customers = Food_hub_Order["customer_id"].value_counts().head(5).reset_index()
top_customers.columns= ["customer_id", "Order_Count"]

print("\nTop Customers:\n",top_customers)
print("\nTop Customers listing:\n", top_customers.columns)

Top Customers:
    customer_id  Order_Count
0        52832           13
1        47440           10
2        83287            9
3       250494            8
4        82041            7

Top Customers listing:
 Index(['customer_id', 'Order_Count'], dtype='str')

In [35]:
Popular_Cusine = Food_hub_Order["cuisine_type"].value_counts()#.max().reset_index()
print("\nPopular Cuisine:\n",Popular_Cusine)

Popular Cuisine:
 cuisine_type
American          584
Japanese          470
Italian           298
Chinese           215
Mexican            77
Indian             73
Middle Eastern     49
Mediterranean      46
Thai               19
French             18
Southern           17
Korean             13
Spanish            12
Vietnamese          7
Name: count, dtype: int64

In [42]:
Food_hub_Order.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24

In [67]:
popular_weekend = Food_hub_Order[Food_hub_Order["day_of_the_week"] == "Weekend"]
popular_weekend.dropna(how = "all", inplace = True)
popular_weekend[["day_of_the_week","cuisine_type"]].value_counts().head()

day_of_the_week  cuisine_type
Weekend          American        415
                 Japanese        335
                 Italian         207
                 Chinese         163
                 Mexican          53
Name: count, dtype: int64